### ISSUE TITLE
So the answer is no right?

### ISSUE THREAD

**Issue by addlistener** [harawata/mybatis-optional-test#1]
This is my result
```

Caused by: java.lang.IllegalStateException: No typehandler found for property name
	at org.apache.ibatis.mapping.ResultMapping$Builder.validate(ResultMapping.java:151)
	at org.apache.ibatis.mapping.ResultMapping$Builder.build(ResultMapping.java:140)
	at org.apache.ibatis.builder.MapperBuilderAssistant.buildResultMapping(MapperBuilderAssistant.java:382)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildResultMappingFromContext(XMLMapperBuilder.java:378)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElement(XMLMapperBuilder.java:280)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElement(XMLMapperBuilder.java:252)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.resultMapElements(XMLMapperBuilder.java:244)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:116)
```

**Comment by harawata** [comment]
Hello @jchnxu ,

The tests in this repo were for this [experimental branch](https://github.com/harawata/mybatis-3/commits/optional).
After discussed with other committers, we decided to apply a [simpler implementation](https://github.com/mybatis/mybatis-3/pull/799).
If you are interested, read this [comment](https://github.com/mybatis/mybatis-3/issues/228#issuecomment-355808461) and its replies for the reason of our decision.
